### ISSUE TITLE
[Feature request] Exit codes for Continuous Integration

### ISSUE THREAD

**Issue by Kristinita** [packagecontrol/package_reviewer#5]
### 1. Summary

I want to add automatic testing my package via Travis CI or other Continuous Integration service. But even if my package contain failures, I get [**exit code 0**](https://travis-ci.org/Kristinita/SashaTravis/builds/204489043).

### 2. Expected behavior

+ if package_reviewer don't find failures and warnings, Travis CI build passed;
+ if package_reviewer find failures and warnings, Travis CI build fail.

### 3. Actual behavior

See [**my build**](https://travis-ci.org/Kristinita/SashaTravis/builds/204489043):

```c++
---

## Report for SashaTravis #############################

### Repository checks ###

Reporting 2 failures:

- Missing a README file

- No semantic version tags found (no tags found at all)

No warnings

### Package checks ###

Reporting 1 failures:

- The binding ['ctrl+a'] unconditionally overrides a default binding

    File: Default (Windows).sublime-keymap

No warnings

For more details on the report messages (for example how to resolve them), go to:

https://github.com/packagecontrol/package_reviewer/wiki

The command "python -m package_reviewer "https://github.com/Kristinita/SashaTravis"" exited with 0.

Done. Your build exited with 0.
```

### 4. Settings

My test Sublime Text package with failures — **<https://github.com/Kristinita/SashaTravis>**.

My `.travis.yml` file:

```yaml
# language
language: python
# Python version
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install virtualenv
  - git clone https://github.com/packagecontrol/package_reviewer.git
  - cd package_reviewer
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m package_reviewer "https://github.com/Kristinita/SashaTravis"
```

### 5. Steps to reproduce

I create test repository and integrate it with Travis CI. I push commit to my repository → package with failures have exit code 0.

Thanks.
